version: '3'
services:
  database:
    image: "austin" # use latest official postgres version

#    volumes:
#      - ./postgressnap:/docker-entrypoint-initdb.d
#      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - "127.0.0.1:5432:5432"
volumes:
  database-data: # named volumes can be managed easier using docker-compose